{
 "title": "Twemproxy Details",
 "tags": [ "application-details" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(twemproxy_exporter_up{job=~\"twemproxy.*\"}, environment)"
    }
   },
   {
    "name": "service_group",
    "label": "Service Group",
    "query": {
     "query": "label_values(twemproxy_exporter_up{job=~\"twemproxy.*\",environment=\"$environment\"}, service_group)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(twemproxy_exporter_up{job=~\"twemproxy.*\",environment=\"$environment\",service_group=~\"$service_group\"}, service_name)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance Name",
    "query": {
     "query": "label_values(twemproxy_exporter_up{job=~\"twemproxy.*\",environment=\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}, instance_name)"
    }
   },
   {
    "name": "instance_ip",
    "label": "Instance IP",
    "query": {
     "query": "label_values(twemproxy_exporter_up{job=~\"twemproxy.*\",environment=\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}, instance_ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Server Responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ceil(irate(twemproxy_exporter_server_responses_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{instance_ip}} | {{server}}"
    }
   ]
  },
  {
   "title": "Total Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ceil(irate(twemproxy_exporter_server_requests_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{instance_ip}} | {{server}}"
    }
   ]
  },
  {
   "title": "Total Server Response (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(twemproxy_exporter_server_responses_bytes_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m])",
     "legendFormat": "{{instance_ip}} | {{server}}"
    }
   ]
  },
  {
   "title": "Total Server Requests (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(twemproxy_exporter_server_requests_bytes_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m])",
     "legendFormat": "{{instance_ip}} | {{server}}"
    }
   ]
  },
  {
   "title": "Queue In/Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ceil(twemproxy_exporter_incoming_queue{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"})",
     "legendFormat": "{{instance_ip}} | {{server}} - IN"
    },
    {
     "expr": "ceil(twemproxy_exporter_outgoing_queue{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"})",
     "legendFormat": "{{instance_ip}} | {{server}} - OUT"
    }
   ]
  },
  {
   "title": "Queue In/Out (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "twemproxy_exporter_incoming_queue_bytes{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}",
     "legendFormat": "{{instance_ip}} | {{server}} - IN"
    },
    {
     "expr": "twemproxy_exporter_outgoing_queue_bytes{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}",
     "legendFormat": "{{instance_ip}} | {{server}} - OUT"
    }
   ]
  },
  {
   "title": "Forward Error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(twemproxy_exporter_forward_errors_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m])",
     "legendFormat": "{{instance_ip}}"
    }
   ]
  },
  {
   "title": "Backend Ejection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ceil(irate(twemproxy_exporter_backend_server_ejections_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{instance_ip}}"
    }
   ]
  },
  {
   "title": "Active Client Connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "twemproxy_exporter_client_connections_active{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}",
     "legendFormat": "{{instance_ip}}"
    }
   ]
  },
  {
   "title": "Active Server Connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "twemproxy_exporter_server_connections_active{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}",
     "legendFormat": "{{instance_ip}} | {{server}}"
    }
   ]
  },
  {
   "title": "Client Connection Problem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "ceil(irate(twemproxy_exporter_client_eof_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{ instance_ip }} - EOF"
    },
    {
     "expr": "ceil(irate(twemproxy_exporter_client_err_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{ instance_ip }} - ERR"
    }
   ]
  },
  {
   "title": "Server Connection Problem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(irate(twemproxy_exporter_server_eof_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{instance_ip}} | {{server}} - EOF"
    },
    {
     "expr": "(irate(twemproxy_exporter_server_err_total{job=~\"twemproxy.*\",service_type=~\"java|golang\",environment=~\"$environment\",service_group=~\"$service_group\",service_name=\"$service_name\"}[1m]))",
     "legendFormat": "{{instance_ip}} | {{server}} - ERR"
    }
   ]
  }
 ]
}